import { Schema, model, Document, Types } from 'mongoose';

export interface ILike {
  userId: Types.ObjectId;
  reaction: 'like' | 'celebrate' | 'support' | 'love' | 'insightful' | 'curious' | 'funny';
}

export interface ILinkPreview {
  title?: string;
  description?: string;
  imageUrl?: string;
  siteName?: string;
}

export interface IPollOption {
  text: string;
  votes: Types.ObjectId[];
}

export interface IComment {
  // Auto-generated by Mongoose subdoc schema (timestamps: true). Optional at
  // creation time so callers can push the inline shape without manually
  // supplying values Mongoose will fill in on save. Always present on read.
  _id?: Types.ObjectId;
  authorId: Types.ObjectId;
  content: string;
  likes: Types.ObjectId[];
  parentCommentId: Types.ObjectId | null;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IPostDocument extends Document {
  authorId: Types.ObjectId;
  type: 'text' | 'image' | 'link' | 'article' | 'poll' | 'verification_announcement';
  content: string;
  imageUrls: string[];
  linkUrl: string;
  linkPreview: ILinkPreview;
  pollOptions: IPollOption[];
  pollDuration: number;
  tags: string[];
  likes: ILike[];
  comments: IComment[];
  reposts: Types.ObjectId[];
  // CRIT-10: repost fields. Previously absent from the schema, so every repost()
  // call silently dropped them and the resulting Post had no link to its original.
  isRepost: boolean;
  originalPostId: Types.ObjectId | null;
  isVerificationAnnouncement: boolean;
  verificationId: Types.ObjectId | null;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const LikeSchema = new Schema<ILike>(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    reaction: {
      type: String,
      enum: ['like', 'celebrate', 'support', 'love', 'insightful', 'curious', 'funny'],
      default: 'like',
    },
  },
  { _id: false }
);

const LinkPreviewSchema = new Schema<ILinkPreview>(
  {
    title: String,
    description: String,
    imageUrl: String,
    siteName: String,
  },
  { _id: false }
);

const PollOptionSchema = new Schema<IPollOption>(
  {
    text: { type: String, required: true, trim: true },
    votes: [{ type: Schema.Types.ObjectId, ref: 'User' }],
  },
  { _id: true }
);

// SCHEMA BUG 5: comments field referenced a 'Comment' model that doesn't exist,
// causing MissingSchemaError on .populate('comments'). Replaced with an
// inline sub-schema so comments are embedded directly in the post document.
const CommentSchema = new Schema<IComment>(
  {
    authorId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    content:  { type: String, trim: true, maxlength: 2000, required: true },
    likes:    [{ type: Schema.Types.ObjectId, ref: 'User' }],
    parentCommentId: { type: Schema.Types.ObjectId, ref: 'Post', default: null },
  },
  { timestamps: true }
);

const PostSchema = new Schema<IPostDocument>(
  {
    authorId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    type: {
      type: String,
      enum: ['text', 'image', 'link', 'article', 'poll', 'verification_announcement'],
      default: 'text',
    },
    content: { type: String, trim: true, maxlength: 5000, default: '' },
    imageUrls: [{ type: String }],
    linkUrl: { type: String, trim: true, default: '' },
    linkPreview: { type: LinkPreviewSchema, default: {} },
    pollOptions: [PollOptionSchema],
    pollDuration: { type: Number, default: 7 },  // days
    tags: [{ type: String, lowercase: true, trim: true }],
    likes: [LikeSchema],
    comments: [CommentSchema],
    reposts: [{ type: Schema.Types.ObjectId, ref: 'User' }],
    // CRIT-10: persist repost link so the feed can hydrate the original post.
    isRepost: { type: Boolean, default: false },
    originalPostId: { type: Schema.Types.ObjectId, ref: 'Post', default: null },
    isVerificationAnnouncement: { type: Boolean, default: false },
    verificationId: { type: Schema.Types.ObjectId, ref: 'Verification', default: null },
    isDeleted: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────

PostSchema.index({ authorId: 1 });
PostSchema.index({ tags: 1 });
PostSchema.index({ createdAt: -1 });
PostSchema.index({ isDeleted: 1 });

export const Post = model<IPostDocument>('Post', PostSchema);
