import {motion,AnimatePresence} from 'framer-motion';
import {X,CheckCircle2,XCircle,Clock,ShieldCheck,Loader2} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {useSessionAudit} from './recruiterApi';
const DIFF_NUM:Record<string,number>={easy:1,medium:2,hard:3};
function ScoreBar({label,value,color}:{label:string;value:number;color:string}){return(<div className="space-y-1"><div className="flex justify-between text-xs"><span className="text-gray-600">{label}</span><span className="font-semibold tabular-nums" style={{color}}>{value}</span></div><div className="h-1.5 bg-gray-100 rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${value}%`,background:color}}/></div></div>);}
export default function SessionAuditDrawer({sessionId,onClose}:{sessionId:string;onClose:()=>void}){
  const{data:audit,isLoading}=useSessionAudit(sessionId);
  const diffData=audit?.answers.map((a,i)=>({q:i+1,difficulty:DIFF_NUM[a.difficulty]??2,isCorrect:a.isCorrect}))??[];
  return(<AnimatePresence><motion.div className="fixed inset-0 z-50 flex" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={e=>e.target===e.currentTarget&&onClose()}>
    <div className="flex-1 bg-black/40" onClick={onClose}/>
    <motion.div initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28,stiffness:300}} className="w-full max-w-2xl bg-white shadow-2xl flex flex-col h-full overflow-hidden">
      <div className="flex items-center justify-between px-6 py-4 border-b shrink-0"><h2 className="font-bold text-gray-900">Session Audit Trail</h2><button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400"><X size={18}/></button></div>
      {isLoading?(<div className="flex-1 flex items-center justify-center text-gray-300"><Loader2 size={28} className="animate-spin"/></div>):!audit?(<div className="flex-1 flex items-center justify-center text-gray-400"><p>Audit unavailable.</p></div>):(
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-6">
          <section><h3 className="font-semibold text-gray-800 text-sm mb-3">Session summary</h3><div className="grid grid-cols-3 gap-3 text-center">{[{label:'Composite',value:audit.session.compositeScore,color:audit.session.compositeScore>=70?'#22c55e':'#ef4444'},{label:'AI probability',value:`${Math.round(audit.session.aiProbability*100)}%`,color:audit.session.aiProbability>0.4?'#ef4444':'#22c55e'},{label:'Strikes',value:`${audit.session.strikeCount}/3`,color:audit.session.strikeCount>=3?'#ef4444':'#6b7280'}].map(item=>(<div key={item.label} className="bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-500 mb-1">{item.label}</p><p className="text-xl font-bold tabular-nums" style={{color:item.color}}>{item.value}</p></div>))}</div></section>
          <section><h3 className="font-semibold text-gray-800 text-sm mb-3">Score breakdown</h3><div className="space-y-2.5"><ScoreBar label="Concept accuracy" value={audit.session.conceptScore} color="#3b82f6"/><ScoreBar label="Speed" value={audit.session.speedScore} color="#8b5cf6"/><ScoreBar label="Consistency" value={audit.session.consistencyScore} color="#06b6d4"/><ScoreBar label="Integrity" value={audit.session.behaviorScore} color="#10b981"/><ScoreBar label="AI authenticity" value={audit.session.aiScore} color="#f59e0b"/></div></section>
          <section><h3 className="font-semibold text-gray-800 text-sm mb-3">Adaptive difficulty curve</h3><div className="bg-gray-50 rounded-xl p-3 h-40"><ResponsiveContainer width="100%" height="100%"><LineChart data={diffData}><CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb"/><XAxis dataKey="q" tick={{fontSize:11}}/><YAxis domain={[0.5,3.5]} ticks={[1,2,3]} tickFormatter={v=>['','Beg','Mid','Adv'][v]??''} tick={{fontSize:11}}/><Tooltip contentStyle={{fontSize:12,borderRadius:8}}/><Line dataKey="difficulty" stroke="#3b82f6" strokeWidth={2} dot={(p)=>{const{cx,cy,payload}=p;return<circle key={`d${payload.q}`} cx={cx} cy={cy} r={4} fill={payload.isCorrect?'#22c55e':payload.isCorrect===false?'#ef4444':'#9ca3af'} stroke="#fff" strokeWidth={1.5}/>;}} /></LineChart></ResponsiveContainer></div></section>
          <section><h3 className="font-semibold text-gray-800 text-sm mb-3">Answer detail</h3><div className="overflow-x-auto rounded-xl border border-gray-200"><table className="w-full text-xs"><thead className="bg-gray-50"><tr>{['#','Type','Diff','✓','TO','Time(s)','Concept','AI%'].map(h=><th key={h} className="text-left px-3 py-2 text-gray-500 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{audit.answers.map((a,i)=>(<tr key={i} className="hover:bg-gray-50"><td className="px-3 py-2 text-gray-500">{i+1}</td><td className="px-3 py-2 capitalize text-gray-700">{a.questionType.replace('-',' ')}</td><td className="px-3 py-2 capitalize text-gray-600">{a.difficulty}</td><td className="px-3 py-2">{a.isCorrect===null?<span className="text-gray-300">—</span>:a.isCorrect?<CheckCircle2 size={14} className="text-green-500"/>:<XCircle size={14} className="text-red-400"/>}</td><td className="px-3 py-2">{a.isTimeout&&<Clock size={13} className="text-amber-500"/>}</td><td className="px-3 py-2 tabular-nums text-gray-600">{(a.timeTaken/1000).toFixed(1)}</td><td className="px-3 py-2 tabular-nums"><span className={a.conceptScore>=70?'text-green-600':'text-red-500'}>{a.conceptScore}</span></td><td className="px-3 py-2 tabular-nums">{a.questionType==='micro-theory'?<span className={a.aiScore>40?'text-red-500 font-semibold':'text-gray-400'}>{a.aiScore}%</span>:<span className="text-gray-300">—</span>}</td></tr>))}</tbody></table></div></section>
          {audit.events.length>0&&<section><h3 className="font-semibold text-gray-800 text-sm mb-3">Behavior event log</h3><div className="space-y-2">{audit.events.map((e,i)=>(<div key={i} className="flex items-center gap-3 text-xs bg-gray-50 rounded-xl px-3 py-2"><div className="font-medium text-gray-600">{e.eventType.replace(/-/g,' ')}</div><div className="text-gray-400">{new Date(e.timestamp).toLocaleTimeString()}</div><div className="text-gray-500 ml-auto">Strike {e.strikeCount}/3</div></div>))}</div></section>}
        </div>
      )}
    </motion.div>
  </motion.div></AnimatePresence>);
}
